spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: root
    password: root
  jpa:
    database: "postgresql"
    show-sql: "true"
    hibernate:
      ddl-auto: "create"
    defer-datasource-initialization: true
  sql:
    init:
      mode: always