spring:
  cloud:
    gateway:
      routes:
        - id: book-admin-api
          uri: lb://book
          predicates:
            - Method=POST
            - Path=/book/, /book/stock
          filters:
            - name: AuthFilter
              args:
                role: Admin
            - RewritePath=/book(?<segment>/?.*), $\{segment}
        - id: book
          uri: lb://book
          predicates:
            - Path=/book/**
          filters:
            - RewritePath=/book(?<segment>/?.*), $\{segment}
        - id: account-not-auth
          uri: lb://account
          predicates:
            - Path=/account/signin
          filters:
            - RewritePath=/account(?<segment>/?.*), $\{segment}
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account(?<segment>/?.*), $\{segment}
            - AuthFilter=User
        - id: rental
          uri: lb://rental
          predicates:
            - Path=/rental/**
          filters:
            - RewritePath=/rental(?<segment>/?.*), $\{segment}
            - AuthFilter=User
