spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  application:
    name: gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/