server:
  port: 8761
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
  profiles:
    active: local
  application:
    name: discovery
